### ISSUE TITLE
Macht  garnichts..

### ISSUE THREAD

**Issue by Andiq** [Krglok/Realms#76]
Wenn ich alle empfohlenen Plugins installiert habe und danach Realms installieren will und in plugins reinkopieren passiert ... nichts und ich habe schon auf verschiedene weisen versucht das zu fixen ( neuer server usw...) braucht man gewiss viel ram zugewiesen?

**Comment by Krglok** [comment]
Du must die Daten ebenfalls installieren . In Update 0.9.5 ist ein zip , in diesem ist alles enthalten.
Siehe auch auf der Projektpage unter
Admin / [installation instruction](http://dev.bukkit.org/bukkit-plugins/realms/pages/admin/installation-instruction/)

Die Daten sind ziemlich komplex und beinhalten eine Datenbank, deshalb werden sie nicht automatisch generiert.

**Comment by Andiq** [comment]
das problem ist, dass ich 1.8 benutze und herostronghold nur bis 1.7.9 herostronghold heißt und jetzt auf 1.8.1 auf townships umgenannt wurde und ich befürchte das das dann mit deinem realms plugin ncihtmehr kompatibel ist .... wenn es dennoch geht bitte erklären wie man das installiert ( komm dem installier guide nicht ganz nach...

**Comment by Krglok** [comment]
aeh...... da muss ich erstmal nachlesen.

**Comment by Andiq** [comment]
ok ich versuchs mal danke für die antwort ich hatte gerade auch probleme mit township stehem momentan mit dem entwickler in contackt und tja der hat auch noch ein paar bugs

**Comment by Andiq** [comment]
und was gefunden?

**Comment by Andiq** [comment]
wie siehts aus?

**Comment by Krglok** [comment]
Es gibt ein Plugin Stronghold. Dies ist eine modiizierte Version von HeroStronghold ohne die neuen features. Die Version arbeitet perfkt mit Realms zusammen . Sie kann auch ohne Realms  betrieben werden.
